### ISSUE TITLE
NoMethodError: undefined method `add_domain_type' for Psych:Module

### ISSUE THREAD

**Issue by kokizzu** [datamapper/dm-serializer#45]
Getting this error since upgrading to `ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]`
```
! Unable to load application: NoMethodError: undefined method `add_domain_type' for Psych:Module
/home/asd/.gem/ruby/2.2.0/gems/dm-serializer-1.2.2/lib/dm-serializer/to_yaml.rb:15:in `included': undefined method `add_domain_type' for Psych:Module (NoMethodError)
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/model.rb:219:in `include'
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/model.rb:219:in `block in extended'
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/model.rb:219:in `each'
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/model.rb:219:in `extended'
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/resource.rb:71:in `extend'
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/resource.rb:71:in `included'
        from /home/asd/.gem/ruby/2.2.0/gems/dm-noisy-failures-0.2.3/lib/data_mapper/noisy_failures.rb:31:in `call'
        from /home/asd/.gem/ruby/2.2.0/gems/dm-noisy-failures-0.2.3/lib/data_mapper/noisy_failures.rb:31:in `included'
```

When `dm-noisy-failures` disabled:

```
! Unable to load application: NoMethodError: undefined method `add_domain_type' for Psych:Module
/home/asd/.gem/ruby/2.2.0/gems/dm-serializer-1.2.2/lib/dm-serializer/to_yaml.rb:15:in `included': undefined method `add_domain_type' for Psych:Module (NoMethodError)
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/model.rb:219:in `include'
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/model.rb:219:in `block in extended'
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/model.rb:219:in `each'
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/model.rb:219:in `extended'
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/resource.rb:71:in `extend'
        from /usr/lib/ruby/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/resource.rb:71:in `included'
```

**Comment by kokizzu** [comment]
```
gem install psych
```
and 

```
require 'psych'
```
after require `data_mapper` solves this problem
